export { GROVIO_LOGO_URL, emailLayout } from './shared'
export { accountRecoveryHtml, accountRecoveryText } from './account-recovery'
export { invoiceHtml, invoiceText } from './invoice'
export { orderConfirmationHtml, orderConfirmationText } from './order-confirmation'
export { scheduledReminderHtml } from './scheduled-reminder'
export { contactToAdminHtml } from './contact-to-admin'
export { contactConfirmationHtml } from './contact-confirmation'
