import type { Product, Category } from "./types"

export const categories: Category[] = [
  {
    id: "vegetables",
    slug: "vegetables",
    name: "Vegetables",
    icon: "https://img.freepik.com/free-psd/vibrant-vegetable-harvest-colorful-collection-fresh-produce_191095-79960.jpg",
    subcategories: ["Leafy Greens", "Root Vegetables", "Fresh Herbs"],
  },
  {
    id: "seasonings",
    slug: "seasonings-spices",
    name: "Seasonings & Spices",
    icon: "https://img.freepik.com/premium-photo/set-different-spices-sauce-bowls_185193-51424.jpg",
    subcategories: ["Cubes", "Powders", "Fresh Spices"],
  },
  {
    id: "dairy",
    slug: "dairy-eggs",
    name: "Dairy & Eggs",
    icon: "https://img.freepik.com/premium-photo/milk-cheese-bottle-dairy_53876-321236.jpg",
    subcategories: ["Milk", "Eggs", "Dairy Products"],
  },
  {
    id: "grains",
    slug: "rice-grains",
    name: "Rice & Grains",
    icon: "https://img.freepik.com/free-photo/view-allergens-commonly-found-grains_23-2150170285.jpg",
    subcategories: ["Local Rice", "Imported Rice", "Other Grains"],
  },
  {
    id: "canned",
    slug: "canned-foods",
    name: "Canned Foods",
    icon: "https://img.freepik.com/premium-photo/open-tin-cans-with-different-preserved-products-wooden-table-flat-lay_495423-118953.jpg",
    subcategories: ["Fish", "Tomato Paste", "Preserved Foods"],
  },
  {
    id: "beverages",
    slug: "beverages",
    name: "Beverages",
    icon: "https://img.freepik.com/free-photo/colorful-soda-drinks-macro-shot_53876-32239.jpg",
    subcategories: ["Hot Drinks", "Soft Drinks", "Juices"],
  },
  {
    id: "pasta",
    slug: "pasta-noodles",
    name: "Pasta & Noodles",
    icon: "https://img.freepik.com/free-photo/front-view-raw-pasta-bowl_141793-17779.jpg",
    subcategories: ["Instant Noodles", "Pasta", "Spaghetti"],
  },
  {
    id: "cereals",
    slug: "breakfast-cereals",
    name: "Breakfast Cereals",
    icon: "https://img.freepik.com/free-vector/breakfast-cereal-plates-realistic-set-with-different-tastes-isolated-vector-illustration_1284-79560.jpg",
    subcategories: ["Corn Flakes", "Granola", "Oatmeal"],
  },
  {
    id: "oils",
    slug: "oils-spreads",
    name: "Oils & Spreads",
    icon: "https://img.freepik.com/free-photo/healthy-product-olive-oil_23-2151944031.jpg",
    subcategories: ["Cooking Oil", "Margarine", "Butter"],
  },
  {
    id: "flour",
    slug: "flour-baking",
    name: "Flour & Baking",
    icon: "https://img.freepik.com/free-photo/stashed-flour-used-cooking_23-2149517214.jpg",
    subcategories: ["All Purpose Flour", "Bread Flour", "Baking Powder"],
  },
  {
    id: "meat",
    slug: "protein",
    name: "Protein",
    icon: "https://img.freepik.com/premium-photo/different-types-raw-meat-steaks-beef-striploin-salmon-chicken-breast-top-view_89816-24154.jpg",
    subcategories: ["Chicken", "Fish", "Beef"],
  },
]

export const sampleProducts: Product[] = [
  // Featured Rice Product (matches screenshot)
  {
    id: "0",
    slug: "royal-basmati-rice-5kg",
    name: "Royal White Basmati Rice",
    description: "Premium quality basmati rice from the foothills of the Himalayas. Naturally aromatic and aged for superior taste and texture. Perfect for biryani, pilaf, and other rice dishes.",
    price: 130,
    originalPrice: 210,
    images: ["/products/royal-rice.png"],
    category: "grains",
    subcategory: "Imported Rice",
    brand: "Royal",
    specifications: {
      size: "5kg",
      weight: "5kg",
      type: "Long-Grain",
      packaging: "Bag",
    },
    inStock: true,
    rating: 4.6,
    reviews: 124,
  },
  // Seasonings & Spices
  {
    id: "1",
    slug: "onga-classic-seasoning-cube",
    name: "Onga Classic Seasoning Cube",
    description: "Premium seasoning cube for authentic Ghanaian taste",
    price: 2.5,
    images: ["https://imgur.com/LGUDj3d.png"],
    category: "seasonings",
    subcategory: "Cubes",
    brand: "Onga",
    specifications: {
      quantity: "12 cubes",
      weight: "120g",
      packaging: "Box",
    },
    inStock: true,
    rating: 4.8,
    reviews: 156,
  },
  {
    id: "2",
    slug: "fresh-rosemary",
    name: "Fresh Rosemary",
    description: "Fresh aromatic rosemary for cooking",
    price: 3.0,
    images: ["https://imgur.com/pJjlGcQ.png"],
    category: "seasonings",
    subcategory: "Fresh Spices",
    brand: "Fresh",
    specifications: {
      weight: "50g",
      type: "Fresh",
      packaging: "Bundle",
    },
    inStock: true,
    rating: 4.6,
    reviews: 89,
  },
  {
    id: "3",
    slug: "black-pepper",
    name: "Black Pepper",
    description: "Premium ground black pepper for seasoning",
    price: 4.5,
    images: ["https://imgur.com/9a3E1pe.png"],
    category: "seasonings",
    subcategory: "Powders",
    brand: "Premium",
    specifications: {
      weight: "100g",
      type: "Ground",
      packaging: "Jar",
    },
    inStock: true,
    rating: 4.7,
    reviews: 203,
  },
  {
    id: "4",
    slug: "mixed-spices",
    name: "Mixed Spices",
    description: "Blend of aromatic spices for cooking",
    price: 5.0,
    images: ["https://imgur.com/A48lNlT.png"],
    category: "seasonings",
    subcategory: "Powders",
    brand: "Traditional",
    specifications: {
      weight: "150g",
      type: "Blend",
      packaging: "Jar",
    },
    inStock: true,
    rating: 4.5,
    reviews: 124,
  },
  {
    id: "5",
    slug: "garlic",
    name: "Garlic",
    description: "Fresh garlic bulbs for cooking",
    price: 8.0,
    images: ["https://imgur.com/u5L7tit.png"],
    category: "vegetables",
    subcategory: "Fresh Herbs",
    brand: "Fresh",
    specifications: {
      weight: "1kg",
      type: "Fresh",
      packaging: "Loose",
    },
    inStock: true,
    rating: 4.9,
    reviews: 78,
  },

  // Dairy & Eggs
  {
    id: "6",
    slug: "fresh-eggs",
    name: "Fresh Eggs",
    description: "Farm fresh eggs from local poultry",
    price: 18.0,
    images: ["https://imgur.com/M3FNVGQ.png"],
    category: "dairy",
    subcategory: "Eggs",
    specifications: {
      quantity: "Half Crate (15 eggs)",
      type: "Fresh",
      packaging: "Crate",
    },
    inStock: true,
    rating: 4.9,
    reviews: 167,
  },
  {
    id: "7",
    slug: "ideal-milk",
    name: "Ideal Milk",
    description: "Premium quality milk for the whole family",
    price: 25.0,
    images: ["https://www.nestle-cwa.com/sites/g/files/pydnoa346/files/asset-library/publishingimages/brands/ideal%20milk%20original%20copy.jpg"],
    category: "dairy",
    subcategory: "Milk",
    brand: "Ideal",
    specifications: {
      weight: "400g",
      type: "Powder",
      packaging: "Tin",
    },
    inStock: true,
    rating: 4.7,
    reviews: 203,
  },
  {
    id: "8",
    slug: "cheese",
    name: "Cheese",
    description: "Fresh cheese for cooking and snacking",
    price: 15.0,
    images: ["https://imgur.com/6utkrD6.png"],
    category: "dairy",
    subcategory: "Dairy Products",
    brand: "Local",
    specifications: {
      weight: "200g",
      type: "Fresh",
      packaging: "Wrap",
    },
    inStock: true,
    rating: 4.6,
    reviews: 124,
  },

  // Grains & Rice
  {
    id: "9",
    slug: "rice-olonka",
    name: "Rice Olonka",
    description: "Premium quality local rice variety",
    price: 45.0,
    images: ["https://imgur.com/YQWKcP1.png"],
    category: "grains",
    subcategory: "Local Rice",
    brand: "Local",
    specifications: {
      weight: "5kg",
      type: "Local",
      packaging: "Bag",
    },
    inStock: true,
    rating: 4.6,
    reviews: 124,
  },
  {
    id: "10",
    slug: "all-purpose-flour",
    name: "All Purpose Flour",
    description: "Versatile flour for all your baking needs",
    price: 12.0,
    images: ["https://imgur.com/lpbN7mV.png"],
    category: "flour",
    subcategory: "All Purpose Flour",
    brand: "Premium",
    specifications: {
      weight: "2kg",
      type: "All Purpose",
      packaging: "Bag",
    },
    inStock: true,
    rating: 4.5,
    reviews: 89,
  },
  {
    id: "11",
    slug: "flour",
    name: "Flour",
    description: "High quality flour for baking",
    price: 10.0,
    images: ["https://imgur.com/8lBu6u4.png"],
    category: "flour",
    subcategory: "All Purpose Flour",
    brand: "Standard",
    specifications: {
      weight: "1kg",
      type: "Standard",
      packaging: "Bag",
    },
    inStock: true,
    rating: 4.4,
    reviews: 67,
  },

  // Canned Foods
  {
    id: "12",
    slug: "sardine",
    name: "Sardine",
    description: "Premium canned sardines in oil",
    price: 8.5,
    images: ["https://imgur.com/2fxgxRF.png"],
    category: "canned",
    subcategory: "Fish",
    brand: "Premium",
    specifications: {
      weight: "120g",
      type: "Canned",
      packaging: "Tin",
    },
    inStock: true,
    rating: 4.7,
    reviews: 156,
  },

  // Vegetables
  {
    id: "13",
    slug: "fresh-tomatoes",
    name: "Fresh Tomatoes",
    description: "Fresh, ripe tomatoes perfect for cooking",
    price: 8.0,
    images: ["https://imgur.com/QthrZc0.png"],
    category: "vegetables",
    subcategory: "Fresh Vegetables",
    specifications: {
      quantity: "1kg",
      type: "Fresh",
      packaging: "Loose",
    },
    inStock: true,
    rating: 4.5,
    reviews: 89,
  },
  {
    id: "14",
    slug: "onions",
    name: "Onions",
    description: "Fresh onions for cooking",
    price: 6.0,
    images: ["https://imgur.com/jQJMxyj.png"],
    category: "vegetables",
    subcategory: "Root Vegetables",
    specifications: {
      weight: "1kg",
      type: "Fresh",
      packaging: "Loose",
    },
    inStock: true,
    rating: 4.4,
    reviews: 78,
  },
  {
    id: "15",
    slug: "cabbage",
    name: "Cabbage",
    description: "Fresh green cabbage",
    price: 7.0,
    images: ["https://imgur.com/1nT82f9.png"],
    category: "vegetables",
    subcategory: "Leafy Greens",
    specifications: {
      weight: "1kg",
      type: "Fresh",
      packaging: "Loose",
    },
    inStock: true,
    rating: 4.3,
    reviews: 56,
  },

  // Meat & Fish
  {
    id: "16",
    slug: "fresh-chicken",
    name: "Fresh Chicken",
    description: "Fresh local chicken meat",
    price: 35.0,
    images: ["https://imgur.com/11wN1aZ.png"],
    category: "meat",
    subcategory: "Chicken",
    brand: "Local",
    specifications: {
      weight: "1kg",
      type: "Fresh",
      packaging: "Wrap",
    },
    inStock: true,
    rating: 4.8,
    reviews: 134,
  },
  {
    id: "17",
    slug: "fresh-fish",
    name: "Fresh Fish",
    description: "Fresh local fish",
    price: 28.0,
    images: ["https://imgur.com/ug67Kwp.png"],
    category: "meat",
    subcategory: "Fish",
    brand: "Local",
    specifications: {
      weight: "1kg",
      type: "Fresh",
      packaging: "Wrap",
    },
    inStock: true,
    rating: 4.7,
    reviews: 98,
  },

  // Pasta & Noodles
  {
    id: "18",
    slug: "indomie-instant-noodles",
    name: "Indomie Instant Noodles",
    description: "Delicious instant noodles for quick meals",
    price: 3.5,
    images: ["https://imgur.com/WQiSzj1.png"],
    category: "pasta",
    subcategory: "Instant Noodles",
    brand: "Indomie",
    specifications: {
      weight: "70g",
      type: "Instant",
      packaging: "Pack",
    },
    inStock: true,
    rating: 4.6,
    reviews: 245,
  },
  {
    id: "19",
    slug: "pasta",
    name: "Pasta",
    description: "Quality pasta for Italian dishes",
    price: 6.0,
    images: ["https://imgur.com/BFjVu2v.png"],
    category: "pasta",
    subcategory: "Pasta",
    brand: "Premium",
    specifications: {
      weight: "500g",
      type: "Dried",
      packaging: "Pack",
    },
    inStock: true,
    rating: 4.5,
    reviews: 89,
  },

  // Breakfast Cereals
  {
    id: "20",
    slug: "corn-flakes",
    name: "Corn Flakes",
    description: "Crispy corn flakes for breakfast",
    price: 12.0,
    images: ["https://imgur.com/EdoI7u7.png"],
    category: "cereals",
    subcategory: "Corn Flakes",
    brand: "Premium",
    specifications: {
      weight: "500g",
      type: "Cereal",
      packaging: "Box",
    },
    inStock: true,
    rating: 4.4,
    reviews: 67,
  },
  {
    id: "21",
    slug: "granola",
    name: "Granola",
    description: "Healthy granola with nuts and fruits",
    price: 18.0,
    images: ["https://imgur.com/0uc5uN1.png"],
    category: "cereals",
    subcategory: "Granola",
    brand: "Healthy",
    specifications: {
      weight: "400g",
      type: "Cereal",
      packaging: "Bag",
    },
    inStock: true,
    rating: 4.6,
    reviews: 89,
  },

  // Oils & Spreads
  {
    id: "22",
    slug: "cooking-oil",
    name: "Cooking Oil",
    description: "Pure cooking oil for all your cooking needs",
    price: 15.0,
    images: ["https://imgur.com/x2pJAId.png"],
    category: "oils",
    subcategory: "Cooking Oil",
    brand: "Pure",
    specifications: {
      weight: "1L",
      type: "Vegetable",
      packaging: "Bottle",
    },
    inStock: true,
    rating: 4.5,
    reviews: 156,
  },
  {
    id: "23",
    slug: "blue-band-margarine",
    name: "Blue Band Margarine",
    description: "Creamy margarine for spreading and cooking",
    price: 8.0,
    images: ["https://imgur.com/DuTS5Ia.png"],
    category: "oils",
    subcategory: "Margarine",
    brand: "Blue Band",
    specifications: {
      weight: "250g",
      type: "Margarine",
      packaging: "Tub",
    },
    inStock: true,
    rating: 4.4,
    reviews: 134,
  },

  // Beverages
  {
    id: "24",
    slug: "milo-chocolate-drink",
    name: "Milo Chocolate Drink",
    description: "Nutritious chocolate malt drink for energy",
    price: 12.5,
    images: ["https://imgur.com/2fxgxRF.png"],
    category: "beverages",
    subcategory: "Hot Drinks",
    brand: "Milo",
    specifications: {
      weight: "400g",
      type: "Powder",
      packaging: "Sachet",
    },
    inStock: true,
    rating: 4.8,
    reviews: 167,
  },
  {
    id: "25",
    slug: "milo-tin",
    name: "Milo Tin",
    description: "Large tin of Milo chocolate drink powder",
    price: 35.0,
    images: ["https://imgur.com/y6iRasp.png"],
    category: "beverages",
    subcategory: "Hot Drinks",
    brand: "Milo",
    specifications: {
      weight: "1kg",
      type: "Powder",
      packaging: "Tin",
    },
    inStock: true,
    rating: 4.8,
    reviews: 234,
  },

  // Other Products
  {
    id: "26",
    slug: "honey",
    name: "Honey",
    description: "Pure natural honey",
    price: 22.0,
    images: ["https://imgur.com/bEV8W18.png"],
    category: "seasonings",
    subcategory: "Natural Sweeteners",
    brand: "Natural",
    specifications: {
      weight: "500g",
      type: "Pure",
      packaging: "Jar",
    },
    inStock: true,
    rating: 4.9,
    reviews: 89,
  },
  {
    id: "27",
    slug: "vinegar",
    name: "Vinegar",
    description: "Apple cider vinegar for cooking and health",
    price: 8.5,
    images: ["https://imgur.com/mXqVhdo.png"],
    category: "seasonings",
    subcategory: "Condiments",
    brand: "Natural",
    specifications: {
      weight: "500ml",
      type: "Apple Cider",
      packaging: "Bottle",
    },
    inStock: true,
    rating: 4.3,
    reviews: 67,
  },
  {
    id: "28",
    slug: "beans",
    name: "Beans",
    description: "Fresh local beans",
    price: 12.0,
    images: ["https://imgur.com/5blpXHk.png"],
    category: "grains",
    subcategory: "Legumes",
    brand: "Local",
    specifications: {
      weight: "1kg",
      type: "Fresh",
      packaging: "Bag",
    },
    inStock: true,
    rating: 4.6,
    reviews: 78,
  },
  {
    id: "29",
    slug: "fresh-fruits",
    name: "Fresh Fruits",
    description: "Assorted fresh seasonal fruits",
    price: 15.0,
    images: ["https://imgur.com/UG1jxmC.png"],
    category: "vegetables",
    subcategory: "Fresh Fruits",
    brand: "Fresh",
    specifications: {
      weight: "1kg",
      type: "Fresh",
      packaging: "Loose",
    },
    inStock: true,
    rating: 4.7,
    reviews: 123,
  },
]
