export const shopBundles = [
  {
    id: "1",
    title: "Student Essentials Pack",
    description: "Perfect starter pack for students - includes rice, seasonings, and basic cooking ingredients",
    image: "/grocery.png",
    originalPrice: 45,
    currentPrice: 35,
    savings: 10,
    rating: 4.8,
    reviews: 156,
    products: ["Royal Basmati Rice", "Onga Seasoning", "Cooking Oil", "Fresh Garlic"],
    category: "Student",
    badge: "Most Popular"
  },
  {
    id: "2", 
    title: "Family Dinner Bundle",
    description: "Everything you need for a complete family dinner - proteins, vegetables, and seasonings",
    image: "/grocery.png",
    originalPrice: 85,
    currentPrice: 65,
    savings: 20,
    rating: 4.6,
    reviews: 89,
    products: ["Fresh Chicken", "Fresh Fish", "Fresh Tomatoes", "Onions", "Mixed Spices"],
    category: "Family",
    badge: "Best Value"
  },
  {
    id: "3",
    title: "Healthy Breakfast Set",
    description: "Start your day right with this nutritious breakfast bundle",
    image: "/grocery.png", 
    originalPrice: 25,
    currentPrice: 18,
    savings: 7,
    rating: 4.7,
    reviews: 203,
    products: ["Fresh Eggs", "Ideal Milk", "Corn Flakes", "Honey"],
    category: "Health",
    badge: "Limited Time"
  },
  {
    id: "4",
    title: "Spice Master Collection",
    description: "Complete spice collection for authentic Ghanaian cooking",
    image: "/grocery.png",
    originalPrice: 30,
    currentPrice: 22,
    savings: 8,
    rating: 4.9,
    reviews: 124,
    products: ["Black Pepper", "Mixed Spices", "Fresh Rosemary", "Garlic"],
    category: "Cooking",
    badge: "Chef's Choice"
  },
  {
    id: "5",
    title: "Weekend BBQ Pack",
    description: "Everything for a perfect weekend barbecue with friends and family",
    image: "/grocery.png",
    originalPrice: 75,
    currentPrice: 55,
    savings: 20,
    rating: 4.5,
    reviews: 78,
    products: ["Fresh Chicken", "Fresh Fish", "Cooking Oil", "Mixed Spices", "Fresh Rosemary"],
    category: "BBQ",
    badge: "Weekend Special"
  },
  {
    id: "6",
    title: "Quick Lunch Combo",
    description: "Fast and easy lunch ingredients for busy weekdays",
    image: "/grocery.png",
    originalPrice: 35,
    currentPrice: 28,
    savings: 7,
    rating: 4.6,
    reviews: 145,
    products: ["Indomie Noodles", "Fresh Eggs", "Cooking Oil", "Black Pepper"],
    category: "Quick Meals",
    badge: "Time Saver"
  },
  {
    id: "7",
    title: "Vegetarian Delight",
    description: "Complete vegetarian meal ingredients for healthy living",
    image: "/grocery.png",
    originalPrice: 40,
    currentPrice: 32,
    savings: 8,
    rating: 4.7,
    reviews: 92,
    products: ["Fresh Tomatoes", "Onions", "Cabbage", "Fresh Rosemary", "Garlic"],
    category: "Vegetarian",
    badge: "Healthy Choice"
  },
  {
    id: "8",
    title: "Baking Essentials",
    description: "All the ingredients you need for delicious homemade baked goods",
    image: "/grocery.png",
    originalPrice: 50,
    currentPrice: 38,
    savings: 12,
    rating: 4.8,
    reviews: 167,
    products: ["All Purpose Flour", "Fresh Eggs", "Ideal Milk", "Honey"],
    category: "Baking",
    badge: "Baker's Favorite"
  },
  {
    id: "9",
    title: "Protein Power Pack",
    description: "High-protein ingredients for fitness enthusiasts and athletes",
    image: "/grocery.png",
    originalPrice: 60,
    currentPrice: 45,
    savings: 15,
    rating: 4.9,
    reviews: 134,
    products: ["Fresh Chicken", "Fresh Fish", "Fresh Eggs", "Ideal Milk", "Cheese"],
    category: "Fitness",
    badge: "Muscle Builder"
  },
  {
    id: "10",
    title: "Smoothie Starter Kit",
    description: "Perfect ingredients for healthy and delicious smoothies",
    image: "/grocery.png",
    originalPrice: 30,
    currentPrice: 24,
    savings: 6,
    rating: 4.6,
    reviews: 88,
    products: ["Fresh Fruits", "Ideal Milk", "Honey", "Fresh Rosemary"],
    category: "Smoothies",
    badge: "Fresh Start"
  },
  {
    id: "11",
    title: "Soup & Stew Bundle",
    description: "Everything needed for hearty soups and stews",
    image: "/grocery.png",
    originalPrice: 45,
    currentPrice: 35,
    savings: 10,
    rating: 4.7,
    reviews: 156,
    products: ["Fresh Chicken", "Fresh Tomatoes", "Onions", "Garlic", "Mixed Spices"],
    category: "Soups",
    badge: "Comfort Food"
  },
  {
    id: "12",
    title: "Pasta Night Special",
    description: "Complete ingredients for a perfect pasta dinner",
    image: "/grocery.png",
    originalPrice: 40,
    currentPrice: 30,
    savings: 10,
    rating: 4.5,
    reviews: 112,
    products: ["Pasta", "Fresh Tomatoes", "Cheese", "Garlic", "Cooking Oil"],
    category: "Italian",
    badge: "Date Night"
  },
  {
    id: "13",
    title: "Rice Bowl Master",
    description: "Create delicious rice bowls with this complete ingredient set",
    image: "/grocery.png",
    originalPrice: 35,
    currentPrice: 28,
    savings: 7,
    rating: 4.8,
    reviews: 203,
    products: ["Royal Basmati Rice", "Fresh Chicken", "Fresh Eggs", "Fresh Tomatoes", "Onions"],
    category: "Rice Bowls",
    badge: "Trending"
  },
  {
    id: "14",
    title: "Spice Rack Upgrade",
    description: "Upgrade your spice collection with premium seasonings",
    image: "/grocery.png",
    originalPrice: 25,
    currentPrice: 18,
    savings: 7,
    rating: 4.9,
    reviews: 89,
    products: ["Black Pepper", "Mixed Spices", "Fresh Rosemary", "Garlic", "Onga Seasoning"],
    category: "Seasonings",
    badge: "Chef's Pick"
  },
  {
    id: "15",
    title: "Healthy Snack Pack",
    description: "Nutritious snacks for between meals",
    image: "/grocery.png",
    originalPrice: 20,
    currentPrice: 15,
    savings: 5,
    rating: 4.6,
    reviews: 76,
    products: ["Fresh Fruits", "Corn Flakes", "Honey", "Fresh Eggs"],
    category: "Snacks",
    badge: "Guilt Free"
  },
  {
    id: "16",
    title: "Dinner Party Host",
    description: "Impress your guests with this complete dinner party bundle",
    image: "/grocery.png",
    originalPrice: 90,
    currentPrice: 70,
    savings: 20,
    rating: 4.8,
    reviews: 145,
    products: ["Fresh Chicken", "Fresh Fish", "Fresh Tomatoes", "Onions", "Mixed Spices", "Cooking Oil"],
    category: "Entertaining",
    badge: "Host's Choice"
  },
  {
    id: "17",
    title: "Quick Breakfast Fix",
    description: "Fast morning meals for busy professionals",
    image: "/grocery.png",
    originalPrice: 22,
    currentPrice: 17,
    savings: 5,
    rating: 4.5,
    reviews: 98,
    products: ["Corn Flakes", "Fresh Eggs", "Ideal Milk", "Honey"],
    category: "Breakfast",
    badge: "Morning Boost"
  },
  {
    id: "18",
    title: "Mediterranean Mix",
    description: "Fresh ingredients for Mediterranean-style cooking",
    image: "/grocery.png",
    originalPrice: 50,
    currentPrice: 38,
    savings: 12,
    rating: 4.7,
    reviews: 123,
    products: ["Fresh Tomatoes", "Onions", "Fresh Rosemary", "Garlic", "Cooking Oil"],
    category: "Mediterranean",
    badge: "Fresh & Light"
  },
  {
    id: "19",
    title: "Comfort Food Classic",
    description: "Traditional comfort food ingredients for cozy meals",
    image: "/grocery.png",
    originalPrice: 40,
    currentPrice: 32,
    savings: 8,
    rating: 4.6,
    reviews: 167,
    products: ["All Purpose Flour", "Fresh Eggs", "Ideal Milk", "Cheese", "Cooking Oil"],
    category: "Comfort",
    badge: "Nostalgic"
  },
  {
    id: "20",
    title: "Energy Boost Bundle",
    description: "High-energy ingredients for active lifestyles",
    image: "/grocery.png",
    originalPrice: 55,
    currentPrice: 42,
    savings: 13,
    rating: 4.8,
    reviews: 134,
    products: ["Royal Basmati Rice", "Fresh Chicken", "Fresh Eggs", "Ideal Milk", "Honey"],
    category: "Energy",
    badge: "Power Pack"
  },
  {
    id: "21",
    title: "Energy Boost Bundle",
    description: "High-energy ingredients for active lifestyles",
    image: "/grocery.png",
    originalPrice: 55,
    currentPrice: 42,
    savings: 13,
    rating: 4.8,
    reviews: 134,
    products: ["Royal Basmati Rice", "Fresh Chicken", "Fresh Eggs", "Ideal Milk", "Honey"],
    category: "Energy",
    badge: "Power Pack"
  }
]